### ISSUE TITLE
support the alternative EPSG 3857

### ISSUE THREAD

**Issue by timwaters** [timwaters/whoots#1]
support the alternative / ESRI favoured EPSG 102113 

EPSG:900913 is the same as EPSG:102113  - we should support it

**Comment by Sibbald** [comment]
To be pedantic it should be GOOGLE::900913 and ESRI::102113 (for version ArcGIS 9.3.1 or earlier).

The authority of EPSG does now have an equivalent code to these which is EPSG::3857 which the urn information is at http://www.epsg-registry.org/export.htm?gml=urn:ogc:def:crs:EPSG::3857 

ArcGIS 10 supports 3857 and 102113.  Google Maps uses 900913 and Bing uses 3857.

**Comment by bhousel** [comment]
Hey @timwaters, this is an old issue - it looks like `EPSG:3857` is the new standard srs that servers tend to prefer these days.  Would you accept a PR to swap 900913 with 3857?

**Comment by timwaters** [comment]
Yeah, it's only a line change. I think all WMS servers would support 3857 now. 

I hope to be able to implement this this weekend - I'll also need to move hosting for it too, and update things for ruby 2.0

**Comment by timwaters** [comment]
okay this should be fixed in the new version so will close. However it is not deployed yet. Will test with the WMS server from @bhousel  Cheers :)

**Comment by timwaters** [comment]
locally: 

`http://0.0.0.0:9292/tms/11/585/781/MD_SixInchImagery/http://geodata.md.gov/imap/services/Imagery/MD_SixInchImagery/MapServer/WmsServer`

gives us

`http://geodata.md.gov/imap/services/Imagery/MD_SixInchImagery/MapServer/WmsServer?bbox=-8590298.986801248,4735426.77632324,-8570731.107560243,4754994.655564245&format=image/png&service=WMS&version=1.1.1&request=GetMap&srs=EPSG:3857&width=256&height=256&layers=MD_SixInchImagery&map=&styles=`

![wmsserver](https://cloud.githubusercontent.com/assets/48941/15076612/7c540ef6-13a2-11e6-89fd-98aadf56b2ce.png)

**Comment by bhousel** [comment]
Great thanks so much!!

**Comment by timwaters** [comment]
okay, deployed, give a go now.

**Comment by bhousel** [comment]
Looks great!
<img width="1036" alt="screenshot 2016-05-09 10 38 57" src="https://cloud.githubusercontent.com/assets/38784/15116685/4f6be544-15d2-11e6-9372-c6c5b138c688.png">
