### ISSUE TITLE
Whoots SetUp in Local Machine

### ISSUE THREAD

**Issue by mobina** [timwaters/whoots#2]
I am very impressed for Whoots WMS proxy tool. Now I want to setup Whoots WMS proxy on my local Sytem . In my Machine,I installed Ruby, What are all other the steps required to make it work from my Machine? Please suggest any documentation? Eagerly waiting for ur reply.

**Comment by timwaters** [comment]
closing due to time spent since.

Note that it's now a Rack application and should be even easier to get running  https://encrypted.google.com/search?hl=en&q=run%20rack%20application
