### ISSUE TITLE
Not found

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [timwaters/whoots#3]
Hello, in August this URL was working: http://whoots.mapwarper.net/tms/z/x/y/870/http://maps.nypl.org/warper/layers/wms/870 now this says NOT FOUND. The examples found in http://whoots.mapwarper.net/ also is showing this error.

**Comment by timwaters** [comment]
These URL templates are for use in a mapping application or library such as LeafletJS and not in a web browser. 

The z/x/y are to be replaced with numbers, e.g. 
11/604/769

http://whoots.mapwarper.net/tms/11/604/769/870/http://maps.nypl.org/warper/layers/wms/870

closing.
