### ISSUE TITLE
WhooTS greets the world instead of proxying Ohio.gov WMS servers

### ISSUE THREAD

**Issue by 1ec5** [timwaters/whoots#4]
The following URL returns “Hello world!”

http://whoots.mapwarper.net/tms/8/68/97/0/http://geo.oit.ohio.gov/arcgis/services/OSIP/osip_best_avail_1ft/ImageServer/WMSServer

Apparently this is because of a faulty regular expression that snags the “hi” in “ohio”:

https://github.com/timwaters/whoots/blob/2f658105e784b1293c088b5a4500215f0a1d41a6/whoots_app.rb#L10-L11

**Comment by timwaters** [comment]
thanks! That /hi/ could really be removed. I'll accept the PR

**Comment by 1ec5** [comment]
:tada: @timwaters, whenever you get a chance, would you mind updating the whoots.mapwarper.net server with the fix? Thank you!

**Comment by timwaters** [comment]
hi @1ec5 I've deployed it, could you try this now?

**Comment by 1ec5** [comment]
It works great, thanks again!
